# Generated by Django 3.1.5 on 2021-01-20 05:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0002_auto_20210120_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='dsSistema',
            field=models.ManyToManyField(help_text='Selecione os sistemas', to='acessos.Sistema', verbose_name='Sistemas'),
        ),
        migrations.AlterField(
            model_name='acesso',
            name='dtUpdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Última alteração'),
        ),
        migrations.CreateModel(
            name='SystemInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dsSistema', models.ForeignKey(help_text='Selecione os sistemas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='acessos.sistema', verbose_name='Sistemas')),
            ],
            options={
                'ordering': ['dsSistema'],
            },
        ),
    ]
