# Generated by Django 3.1.5 on 2021-01-20 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0003_auto_20210120_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminstance',
            name='dsMatricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acessos.acesso', verbose_name='Matricula'),
        ),
    ]
