# Generated by Django 3.1.5 on 2021-01-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0005_auto_20210120_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminstance',
            name='dsStatus',
            field=models.BooleanField(default=True, help_text='Deseja manter o acesso ativo?', verbose_name='Status'),
        ),
    ]
