# Generated by Django 3.1.5 on 2021-01-20 05:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0006_auto_20210120_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
