# Generated by Django 3.1.5 on 2021-01-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0007_auto_20210120_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsPeriodo', models.IntegerField(help_text='AAAAMM', unique=True, verbose_name='Período de avaliação')),
                ('blStatusPerido', models.BooleanField(default=False, help_text='Ativo/Fechado', verbose_name='Período Ativo?')),
            ],
        ),
        migrations.AddField(
            model_name='acesso',
            name='dsUserEmail',
            field=models.EmailField(default='email@email.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='dsObs',
            field=models.CharField(help_text='Informações sobre como cancelar o acesso', max_length=500, null=True, verbose_name='Observações sobre os Acessos:'),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='dsNome',
            field=models.CharField(help_text='Insira um sistema aqui .. (ex: SAP HANA)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='systeminstance',
            name='dsStatus',
            field=models.CharField(choices=[('1', 'Manter'), ('0', 'Remover')], default='1', help_text='Deseja manter o acesso ativo?', max_length=1, verbose_name='Status'),
        ),
    ]
