# Generated by Django 3.1.5 on 2021-01-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0008_auto_20210131_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='dsUserEmail',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
