# Generated by Django 3.1.5 on 2021-02-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0009_auto_20210131_0302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avaliacao',
            new_name='CicloAvaliacao',
        ),
    ]
