# Generated by Django 3.1.5 on 2021-02-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0010_auto_20210215_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminstance',
            name='dsCiclo',
            field=models.ForeignKey(default=202101, on_delete=django.db.models.deletion.PROTECT, to='acessos.cicloavaliacao', verbose_name='Ciclo de avaliação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acesso',
            name='dsArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='acessos.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='systeminstance',
            name='dsMatricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='acessos.acesso', verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='systeminstance',
            name='dsSistema',
            field=models.ForeignKey(help_text='Selecione os sistemas', null=True, on_delete=django.db.models.deletion.PROTECT, to='acessos.sistema', verbose_name='Sistemas'),
        ),
    ]
