# Generated by Django 3.1.5 on 2021-02-15 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0011_auto_20210215_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminstance',
            name='dsCiclo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='acessos.cicloavaliacao', verbose_name='Ciclo de avaliação'),
        ),
    ]
