# Generated by Django 3.1.5 on 2021-02-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0012_auto_20210215_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systeminstance',
            name='dsCiclo',
        ),
        migrations.AddField(
            model_name='acesso',
            name='dsSistema',
            field=models.ManyToManyField(to='acessos.Sistema'),
        ),
    ]
