# Generated by Django 3.1.5 on 2021-02-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0013_auto_20210221_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CicloAvaliacao',
        ),
        migrations.AlterField(
            model_name='acesso',
            name='dsSistema',
            field=models.ManyToManyField(to='acessos.Sistema', verbose_name='Acessos Ativos'),
        ),
        migrations.DeleteModel(
            name='SystemInstance',
        ),
    ]
