# Generated by Django 3.1.5 on 2021-03-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0014_auto_20210221_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsNome', models.CharField(help_text='Insira uma pasta .. (ex: 13_MIS)', max_length=100, unique=True)),
                ('dsCaminho', models.CharField(help_text='Insira o caminho completo', max_length=100, unique=True)),
                ('dsObs', models.CharField(help_text='Informações sobre como cancelar/solicitar o acesso', max_length=500, null=True, verbose_name='Observações sobre os Acessos:')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsNome', models.CharField(help_text='Insira um sistema aqui .. (ex: SAP HANA)', max_length=100, unique=True)),
                ('dsObs', models.CharField(help_text='Informações sobre como cancelar/solicitar o acesso', max_length=500, null=True, verbose_name='Observações sobre os Acessos:')),
            ],
        ),
        migrations.AlterField(
            model_name='acesso',
            name='dsSistema',
            field=models.ManyToManyField(blank=True, to='acessos.Sistema', verbose_name='Acessos internos'),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='dsObs',
            field=models.CharField(help_text='Informações sobre como cancelar/solicitar o acesso', max_length=500, null=True, verbose_name='Observações sobre os Acessos:'),
        ),
        migrations.AddField(
            model_name='acesso',
            name='dsRede',
            field=models.ManyToManyField(blank=True, to='acessos.Rede', verbose_name='Pastas de rede'),
        ),
        migrations.AddField(
            model_name='acesso',
            name='dsSistemaExterno',
            field=models.ManyToManyField(blank=True, to='acessos.SistemaExterno', verbose_name='Acessos externos'),
        ),
    ]
