# Generated by Django 3.1.5 on 2021-03-03 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0015_auto_20210303_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='dsCoordenadorEmail',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='Email do Coordenador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='dsKeyUserEmail',
            field=models.EmailField(max_length=254, verbose_name='Email do KeyUser'),
        ),
        migrations.AlterField(
            model_name='rede',
            name='dsCaminho',
            field=models.CharField(help_text='Insira o caminho completo', max_length=100, unique=True, verbose_name='Caminho da pasta:'),
        ),
        migrations.AlterField(
            model_name='rede',
            name='dsNome',
            field=models.CharField(help_text='Insira uma pasta .. (ex: 13_MIS)', max_length=100, unique=True, verbose_name='Nome da pasta:'),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='dsNome',
            field=models.CharField(help_text='Insira um sistema aqui .. (ex: SAP HANA)', max_length=100, unique=True, verbose_name='Nome do sistema:'),
        ),
        migrations.AlterField(
            model_name='sistemaexterno',
            name='dsNome',
            field=models.CharField(help_text='Insira um sistema aqui .. (ex: SAP HANA)', max_length=100, unique=True, verbose_name='Nome do sistma exteno:'),
        ),
    ]
