# Generated by Django 3.1.5 on 2021-03-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0016_auto_20210303_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaexterno',
            name='dsLink',
            field=models.CharField(default='http://', help_text='Http://...', max_length=200, unique=True, verbose_name='Link de acesso:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sistemaexterno',
            name='dsNome',
            field=models.CharField(help_text='Insira um sistema aqui .. (ex: SAP HANA)', max_length=100, unique=True, verbose_name='Nome do sistema exteno:'),
        ),
    ]
