# Generated by Django 3.1.5 on 2021-03-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0017_auto_20210303_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso',
            name='dsUserWeb',
            field=models.CharField(default='usuario', max_length=100, unique=True, verbose_name='Usuário de rede'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acesso',
            name='dsUsuario',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
