# Generated by Django 3.1.5 on 2021-03-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0018_auto_20210303_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='dsSistema',
            field=models.ManyToManyField(blank=True, to='acessos.Sistema', verbose_name='Sistemas internos'),
        ),
        migrations.AlterField(
            model_name='acesso',
            name='dsSistemaExterno',
            field=models.ManyToManyField(blank=True, to='acessos.SistemaExterno', verbose_name='Sistemas externos'),
        ),
    ]
