# Generated by Django 3.1.5 on 2021-03-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0019_auto_20210305_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='dsMatricula',
            field=models.CharField(max_length=10, unique=True, verbose_name='Matricula'),
        ),
    ]
