# Generated by Django 3.1.5 on 2021-03-11 21:01

import acessos.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0021_auto_20210305_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso',
            name='coTeste',
            field=acessos.models.UpperCaseCharField(max_length=10, null=True, verbose_name='teste'),
        ),
    ]
