# Generated by Django 3.1.5 on 2021-03-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0022_acesso_coteste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acesso',
            name='coTeste',
        ),
    ]
